---
- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa).
  hosts: ubuntuserver2
  
  vars:
    ssh_key_filename: id_rsa

  tasks:
  - name: Generate {{ ssh_key_filename }} key pair.
    openssh_keypair:
      #path: /home/$USER/.ssh/id_ssh_rsa
      path: ~/.ssh/{{ ssh_key_filename }}
      type: rsa
      state: present
      mode: 0600