---
- hosts: localhost
  become: yes
  gather_facts: no

  pre_tasks:
  - name: Update apt cache if required.
    apt:
     update_cache: yes
     cache_valid_time: 3600

  roles:
   - install-diodonclipboard
   - install-sublimetext
   - install-vim
   - ubuntu-install-adobereader
   - ubuntu-install-git
   - ubuntu-install-python