---
- hosts: ubuntuservers
  become: true

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
    - name: Print message
      debug:
        msg: Restarting sshd service on {{ inventory_hostname }} with IP Address = {{ ansible_default_ipv4.address }}.

  pre_tasks:
    - name: Backup SSH config file.
      copy:
        src: /etc/ssh/sshd_config
        remote_src: yes
        dest: /etc/ssh/sshd_config.bak
        owner: root
        group: root
        mode: '0644'
        backup: yes

  tasks:
  - name: Verify and Secures SSH.
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
      - regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
    notify: 
      - Print message
      - Restart SSH