# 
# Warning: Please note that Adobe no longer supports Acrobat Reader for Linux.
#          The latest native Linux version is 9.5.5 dated from 26/04/2013. 
#          From this reason you should refrain using/installing Adobe Acrobat Reader to avoid potential vulnerabilities and hacker exploits.
#          You are recommended to consider installation of Adobe Acrobat Reader on Wine.
# Reference: https://linuxconfig.org/how-to-install-adobe-acrobat-reader-on-ubuntu-22-04-jammy-jellyfish-linux
#

---
- name: Run pre-task.
  import_tasks:
    file: pre_task.yml

- name: Install prerequisites for Adobe Reader.
  apt:
   name:
    - libxml2:i386
    - libcanberra-gtk-module:i386 
    - gtk2-engines-murrine:i386 
    - libatk-adaptor:i386
    - libgdk-pixbuf-xlib-2.0-0:i386
   state: latest
 
- name: Download Adobe Reader .deb package.
  get_url:
    url: "{{ dl_server }}{{ package }}"
    dest: /tmp/{{ package }}

- name: Run post_task.
  import_tasks:
    file: post_task.yml